// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.5
// source: pkg/starstore/starstore.proto

package starstore

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StarReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StarId string `protobuf:"bytes,1,opt,name=starId,proto3" json:"starId,omitempty"`
}

func (x *StarReq) Reset() {
	*x = StarReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_starstore_starstore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarReq) ProtoMessage() {}

func (x *StarReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_starstore_starstore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarReq.ProtoReflect.Descriptor instead.
func (*StarReq) Descriptor() ([]byte, []int) {
	return file_pkg_starstore_starstore_proto_rawDescGZIP(), []int{0}
}

func (x *StarReq) GetStarId() string {
	if x != nil {
		return x.StarId
	}
	return ""
}

type OptionalStarResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *OptionalStarResp_Star `protobuf:"bytes,1,opt,name=resp,proto3,oneof" json:"resp,omitempty"`
}

func (x *OptionalStarResp) Reset() {
	*x = OptionalStarResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_starstore_starstore_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionalStarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalStarResp) ProtoMessage() {}

func (x *OptionalStarResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_starstore_starstore_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalStarResp.ProtoReflect.Descriptor instead.
func (*OptionalStarResp) Descriptor() ([]byte, []int) {
	return file_pkg_starstore_starstore_proto_rawDescGZIP(), []int{1}
}

func (x *OptionalStarResp) GetResp() *OptionalStarResp_Star {
	if x != nil {
		return x.Resp
	}
	return nil
}

type OptionalStarResp_Star struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias             []string  `protobuf:"bytes,3,rep,name=alias,proto3" json:"alias,omitempty"`
	Constellation     string    `protobuf:"bytes,4,opt,name=constellation,proto3" json:"constellation,omitempty"`
	Coordinates       []float32 `protobuf:"fixed32,5,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	Distance          float32   `protobuf:"fixed32,6,opt,name=distance,proto3" json:"distance,omitempty"`
	ApparentMagnitude float32   `protobuf:"fixed32,7,opt,name=apparentMagnitude,proto3" json:"apparentMagnitude,omitempty"`
}

func (x *OptionalStarResp_Star) Reset() {
	*x = OptionalStarResp_Star{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_starstore_starstore_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionalStarResp_Star) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalStarResp_Star) ProtoMessage() {}

func (x *OptionalStarResp_Star) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_starstore_starstore_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalStarResp_Star.ProtoReflect.Descriptor instead.
func (*OptionalStarResp_Star) Descriptor() ([]byte, []int) {
	return file_pkg_starstore_starstore_proto_rawDescGZIP(), []int{1, 0}
}

func (x *OptionalStarResp_Star) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OptionalStarResp_Star) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OptionalStarResp_Star) GetAlias() []string {
	if x != nil {
		return x.Alias
	}
	return nil
}

func (x *OptionalStarResp_Star) GetConstellation() string {
	if x != nil {
		return x.Constellation
	}
	return ""
}

func (x *OptionalStarResp_Star) GetCoordinates() []float32 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *OptionalStarResp_Star) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *OptionalStarResp_Star) GetApparentMagnitude() float32 {
	if x != nil {
		return x.ApparentMagnitude
	}
	return 0
}

var File_pkg_starstore_starstore_proto protoreflect.FileDescriptor

var file_pkg_starstore_starstore_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x74, 0x61, 0x72, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f,
	0x73, 0x74, 0x61, 0x72, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x07,
	0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x72, 0x49, 0x64, 0x22,
	0xa1, 0x02, 0x0a, 0x10, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65,
	0x73, 0x70, 0x88, 0x01, 0x01, 0x1a, 0xd2, 0x01, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x73,
	0x74, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20,
	0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x02, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x11,
	0x61, 0x70, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x67, 0x6e, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x11, 0x61, 0x70, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x4d, 0x61, 0x67, 0x6e, 0x69, 0x74, 0x75, 0x64, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x32, 0x79, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x12, 0x42, 0x0a, 0x0c, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x72, 0x73,
	0x12, 0x16, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x28, 0x01, 0x12, 0x28, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x72, 0x12,
	0x08, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0f,
	0x5a, 0x0d, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x74, 0x61, 0x72, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_starstore_starstore_proto_rawDescOnce sync.Once
	file_pkg_starstore_starstore_proto_rawDescData = file_pkg_starstore_starstore_proto_rawDesc
)

func file_pkg_starstore_starstore_proto_rawDescGZIP() []byte {
	file_pkg_starstore_starstore_proto_rawDescOnce.Do(func() {
		file_pkg_starstore_starstore_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_starstore_starstore_proto_rawDescData)
	})
	return file_pkg_starstore_starstore_proto_rawDescData
}

var file_pkg_starstore_starstore_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_starstore_starstore_proto_goTypes = []interface{}{
	(*StarReq)(nil),               // 0: StarReq
	(*OptionalStarResp)(nil),      // 1: OptionalStarResp
	(*OptionalStarResp_Star)(nil), // 2: OptionalStarResp.Star
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
}
var file_pkg_starstore_starstore_proto_depIdxs = []int32{
	2, // 0: OptionalStarResp.resp:type_name -> OptionalStarResp.Star
	2, // 1: StarStore.PersistStars:input_type -> OptionalStarResp.Star
	0, // 2: StarStore.GetStar:input_type -> StarReq
	3, // 3: StarStore.PersistStars:output_type -> google.protobuf.Empty
	1, // 4: StarStore.GetStar:output_type -> OptionalStarResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_starstore_starstore_proto_init() }
func file_pkg_starstore_starstore_proto_init() {
	if File_pkg_starstore_starstore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_starstore_starstore_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StarReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_starstore_starstore_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionalStarResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_starstore_starstore_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionalStarResp_Star); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_starstore_starstore_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_starstore_starstore_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_starstore_starstore_proto_goTypes,
		DependencyIndexes: file_pkg_starstore_starstore_proto_depIdxs,
		MessageInfos:      file_pkg_starstore_starstore_proto_msgTypes,
	}.Build()
	File_pkg_starstore_starstore_proto = out.File
	file_pkg_starstore_starstore_proto_rawDesc = nil
	file_pkg_starstore_starstore_proto_goTypes = nil
	file_pkg_starstore_starstore_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StarStoreClient is the client API for StarStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StarStoreClient interface {
	PersistStars(ctx context.Context, opts ...grpc.CallOption) (StarStore_PersistStarsClient, error)
	GetStar(ctx context.Context, in *StarReq, opts ...grpc.CallOption) (*OptionalStarResp, error)
}

type starStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewStarStoreClient(cc grpc.ClientConnInterface) StarStoreClient {
	return &starStoreClient{cc}
}

func (c *starStoreClient) PersistStars(ctx context.Context, opts ...grpc.CallOption) (StarStore_PersistStarsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StarStore_serviceDesc.Streams[0], "/StarStore/PersistStars", opts...)
	if err != nil {
		return nil, err
	}
	x := &starStorePersistStarsClient{stream}
	return x, nil
}

type StarStore_PersistStarsClient interface {
	Send(*OptionalStarResp_Star) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type starStorePersistStarsClient struct {
	grpc.ClientStream
}

func (x *starStorePersistStarsClient) Send(m *OptionalStarResp_Star) error {
	return x.ClientStream.SendMsg(m)
}

func (x *starStorePersistStarsClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *starStoreClient) GetStar(ctx context.Context, in *StarReq, opts ...grpc.CallOption) (*OptionalStarResp, error) {
	out := new(OptionalStarResp)
	err := c.cc.Invoke(ctx, "/StarStore/GetStar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StarStoreServer is the server API for StarStore service.
type StarStoreServer interface {
	PersistStars(StarStore_PersistStarsServer) error
	GetStar(context.Context, *StarReq) (*OptionalStarResp, error)
}

// UnimplementedStarStoreServer can be embedded to have forward compatible implementations.
type UnimplementedStarStoreServer struct {
}

func (*UnimplementedStarStoreServer) PersistStars(StarStore_PersistStarsServer) error {
	return status.Errorf(codes.Unimplemented, "method PersistStars not implemented")
}
func (*UnimplementedStarStoreServer) GetStar(context.Context, *StarReq) (*OptionalStarResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStar not implemented")
}

func RegisterStarStoreServer(s *grpc.Server, srv StarStoreServer) {
	s.RegisterService(&_StarStore_serviceDesc, srv)
}

func _StarStore_PersistStars_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StarStoreServer).PersistStars(&starStorePersistStarsServer{stream})
}

type StarStore_PersistStarsServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*OptionalStarResp_Star, error)
	grpc.ServerStream
}

type starStorePersistStarsServer struct {
	grpc.ServerStream
}

func (x *starStorePersistStarsServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *starStorePersistStarsServer) Recv() (*OptionalStarResp_Star, error) {
	m := new(OptionalStarResp_Star)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StarStore_GetStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarStoreServer).GetStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StarStore/GetStar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarStoreServer).GetStar(ctx, req.(*StarReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _StarStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StarStore",
	HandlerType: (*StarStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStar",
			Handler:    _StarStore_GetStar_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PersistStars",
			Handler:       _StarStore_PersistStars_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/starstore/starstore.proto",
}
